// Island Burgers & Bites — Menu Data

import { MenuItem, Topping, CategoryInfo } from "./types";

export const categories: CategoryInfo[] = [
  { id: "burgers", label: "Burgers" },
  { id: "cheesesteaks", label: "Cheesesteaks" },
  { id: "hot-dogs", label: "Hot Dogs" },
  { id: "chicken", label: "Chicken" },
  { id: "sides", label: "Sides" },
  { id: "shakes-drinks", label: "Shakes & Drinks" },
  { id: "beer-wine", label: "Beer & Wine" },
];

export const freeToppings: Topping[] = [
  { id: "lettuce", name: "Lettuce", price: 0, category: "free" },
  { id: "tomato", name: "Tomato", price: 0, category: "free" },
  { id: "onion", name: "Onion", price: 0, category: "free" },
  { id: "pickles", name: "Pickles", price: 0, category: "free" },
  { id: "relish", name: "Relish", price: 0, category: "free" },
  { id: "slaw", name: "Slaw", price: 0, category: "free" },
  { id: "chili", name: "Chili", price: 0, category: "free" },
  { id: "mustard", name: "Mustard", price: 0, category: "free" },
  { id: "mayo", name: "Mayo", price: 0, category: "free" },
  { id: "ketchup", name: "Ketchup", price: 0, category: "free" },
];

export const premiumToppings: Topping[] = [
  { id: "candied-bacon", name: "Candied Bacon", price: 1.5, category: "premium" },
  { id: "fried-egg", name: "Fried Egg", price: 1.0, category: "premium" },
  { id: "pimento-cheese", name: "Pimento Cheese", price: 1.0, category: "premium" },
  { id: "sriracha-relish", name: "Sriracha Relish", price: 0.75, category: "premium" },
  { id: "extra-patty", name: "Extra Patty", price: 2.5, category: "premium" },
];

export const menuItems: MenuItem[] = [
  // Burgers
  {
    id: "single-burger",
    name: "Single Burger",
    description: "1/3 lb hand-pattied smash patty on a brioche bun. Simple. Perfect.",
    price: 7.99,
    category: "burgers",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=400&fit=crop",
    customizable: true,
  },
  {
    id: "double-burger",
    name: "Double Burger",
    description: "2/3 lb of smashed beef. Two patties, double the glory.",
    price: 10.99,
    category: "burgers",
    image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&h=400&fit=crop",
    customizable: true,
  },
  {
    id: "bacon-burger",
    name: "Bacon Burger",
    description: "Single patty topped with our house candied bacon. Sweet, salty, smoky.",
    price: 9.49,
    category: "burgers",
    image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&h=400&fit=crop",
    customizable: true,
  },
  {
    id: "bacon-double",
    name: "Bacon Double",
    description: "The crowd favorite. Two patties, candied bacon, your choice of toppings. Absurdly good.",
    price: 12.49,
    category: "burgers",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&h=400&fit=crop",
    customizable: true,
    featured: true,
    badge: "Fan Favorite",
  },
  {
    id: "mushroom-swiss",
    name: "Mushroom Swiss Burger",
    description: "Sauteed mushrooms and melted Swiss on a smash patty. Earthy and rich.",
    price: 9.99,
    category: "burgers",
    image: "https://images.unsplash.com/photo-1572802419224-296b0aeee15d?w=600&h=400&fit=crop",
    customizable: true,
  },
  {
    id: "pimento-burger",
    name: "Pimento Cheese Burger",
    description: "Southern pimento cheese melted over a hand-pattied smash patty. Carolina classic.",
    price: 9.99,
    category: "burgers",
    image: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=600&h=400&fit=crop",
    customizable: true,
  },
  {
    id: "jalapeno-burger",
    name: "Jalapeno Burger",
    description: "Fresh jalapenos with pepper jack cheese. Brings the heat.",
    price: 9.49,
    category: "burgers",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&h=400&fit=crop",
    customizable: true,
  },
  {
    id: "island-burger",
    name: "Island Burger",
    description: "Our signature. Double patty, candied bacon, grilled onions, jalapenos, and special sauce. The one that started it all.",
    price: 13.99,
    category: "burgers",
    image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&h=400&fit=crop",
    customizable: true,
    featured: true,
    badge: "Signature",
  },

  // Cheesesteaks
  {
    id: "classic-philly",
    name: "Classic Philly Cheesesteak",
    description: "Shaved ribeye on the flat-top. Cheez Whiz or provolone. Peppers, onions. Pure.",
    price: 11.99,
    category: "cheesesteaks",
    image: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=600&h=400&fit=crop",
    customizable: false,
    featured: true,
  },
  {
    id: "chicken-cheesesteak",
    name: "Chicken Cheesesteak",
    description: "Grilled chicken with melted cheese, peppers, and onions on a hoagie roll.",
    price: 10.99,
    category: "cheesesteaks",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "mushroom-cheesesteak",
    name: "Mushroom Cheesesteak",
    description: "Shaved ribeye loaded with sauteed mushrooms and melted provolone.",
    price: 12.49,
    category: "cheesesteaks",
    image: "https://images.unsplash.com/photo-1513185158878-8d8c2a2a3da3?w=600&h=400&fit=crop",
    customizable: false,
  },

  // Hot Dogs
  {
    id: "classic-dog",
    name: "Classic All-Beef Dog",
    description: "All-beef frank on a toasted bun. Keep it simple.",
    price: 4.99,
    category: "hot-dogs",
    image: "https://images.unsplash.com/photo-1612392062126-47a14e2e5e3d?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "chili-cheese-dog",
    name: "Chili Cheese Dog",
    description: "All-beef dog smothered in house chili and melted cheese.",
    price: 6.49,
    category: "hot-dogs",
    image: "https://images.unsplash.com/photo-1619740455993-9e612b1af08a?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "slaw-dog",
    name: "Slaw Dog",
    description: "Carolina-style with homemade slaw, mustard, and onions.",
    price: 5.49,
    category: "hot-dogs",
    image: "https://images.unsplash.com/photo-1613483187798-82a59a4f89fa?w=600&h=400&fit=crop",
    customizable: false,
  },

  // Chicken
  {
    id: "fried-chicken-sandwich",
    name: "Fried Chicken Sandwich",
    description: "Crispy fried chicken breast with pickles and mayo on a brioche bun.",
    price: 9.99,
    category: "chicken",
    image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "grilled-chicken-sandwich",
    name: "Grilled Chicken Sandwich",
    description: "Marinated grilled chicken with lettuce, tomato, and our house sauce.",
    price: 9.49,
    category: "chicken",
    image: "https://images.unsplash.com/photo-1521305916504-4a1121188589?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "chicken-salad-sandwich",
    name: "Southern Chicken Salad",
    description: "Homemade chicken salad with a Southern twist. Light and satisfying.",
    price: 8.99,
    category: "chicken",
    image: "https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?w=600&h=400&fit=crop",
    customizable: false,
  },

  // Sides
  {
    id: "crinkle-fries",
    name: "Crinkle-Cut Fries",
    description: "Seasoned crinkle-cut fries, hand-dipped in hot oil. Crispy every time.",
    price: 3.99,
    category: "sides",
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "loaded-fries",
    name: "Loaded Fries",
    description: "Crinkle fries topped with house chili and melted cheese. A meal by itself.",
    price: 6.99,
    category: "sides",
    image: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "onion-rings",
    name: "Onion Rings",
    description: "Beer-battered and fried golden. Crunchy outside, sweet inside.",
    price: 4.99,
    category: "sides",
    image: "https://images.unsplash.com/photo-1639024471283-03518883512d?w=600&h=400&fit=crop",
    customizable: false,
  },

  // Shakes & Drinks
  {
    id: "milkshake-vanilla",
    name: "Vanilla Milkshake",
    description: "Thick, handspun vanilla milkshake. Real ice cream, real good.",
    price: 5.99,
    category: "shakes-drinks",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&h=400&fit=crop",
    customizable: false,
    featured: true,
  },
  {
    id: "milkshake-chocolate",
    name: "Chocolate Milkshake",
    description: "Rich chocolate milkshake, handspun and impossibly thick.",
    price: 5.99,
    category: "shakes-drinks",
    image: "https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "milkshake-strawberry",
    name: "Strawberry Milkshake",
    description: "Fresh strawberry milkshake. Sweet, creamy, and pink.",
    price: 5.99,
    category: "shakes-drinks",
    image: "https://images.unsplash.com/photo-1579954115563-e72bf1381629?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "milkshake-pb",
    name: "Peanut Butter Milkshake",
    description: "Peanut butter and ice cream blended into something beautiful.",
    price: 5.99,
    category: "shakes-drinks",
    image: "https://images.unsplash.com/photo-1553787499-6f9133860278?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "milkshake-oreo",
    name: "Oreo Milkshake",
    description: "Crushed Oreos in a handspun shake. Cookies and cream perfection.",
    price: 6.49,
    category: "shakes-drinks",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "fountain-drink",
    name: "Fountain Drink",
    description: "Coca-Cola, Sprite, Dr Pepper, Lemonade, Sweet Tea.",
    price: 2.49,
    category: "shakes-drinks",
    image: "https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=600&h=400&fit=crop",
    customizable: false,
  },

  // Beer & Wine
  {
    id: "draft-ipa",
    name: "Local IPA (Draft)",
    description: "Rotating local IPA on tap. Ask your server what's pouring today.",
    price: 6.00,
    category: "beer-wine",
    image: "https://images.unsplash.com/photo-1566633806327-68e152aaf26d?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "draft-lager",
    name: "House Lager (Draft)",
    description: "Light, crisp, and cold. The perfect burger companion.",
    price: 5.00,
    category: "beer-wine",
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "bud-light",
    name: "Bud Light",
    description: "Classic American light beer. Ice cold every time.",
    price: 4.00,
    category: "beer-wine",
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "corona",
    name: "Corona Extra",
    description: "Mexican lager with a lime. Beach vibes in a bottle.",
    price: 5.00,
    category: "beer-wine",
    image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "white-claw",
    name: "White Claw Seltzer",
    description: "Hard seltzer. Mango, Black Cherry, or Lime. Light and refreshing.",
    price: 5.00,
    category: "beer-wine",
    image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "house-white",
    name: "House White Wine",
    description: "Chardonnay or Pinot Grigio by the glass. Crisp and easy-drinking.",
    price: 7.00,
    category: "beer-wine",
    image: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=600&h=400&fit=crop",
    customizable: false,
  },
  {
    id: "house-red",
    name: "House Red Wine",
    description: "Cabernet Sauvignon or Merlot by the glass. Smooth and full-bodied.",
    price: 7.00,
    category: "beer-wine",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&h=400&fit=crop",
    customizable: false,
  },
];
